# .air.toml
# Config file for air: https://github.com/cosmtrek/air

root = "."          # working directory root
tmp_dir = "tmp"     # temporary directory for builds

[build]
  cmd = "go build -o ./tmp/main ." # build command
  bin = "tmp/main"                 # executable binary path
  # Folders/files to watch for changes
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  log = "air_build.log" # build log file
  delay = 1000 # delay in milliseconds before build

[log]
  time = true # show time in log

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true# .air.toml
